# Generated by Django 5.0.2 on 2025-04-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(help_text='Professional title', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('bio_short', models.TextField(help_text='Short biography for homepage')),
                ('bio_long', models.TextField(help_text='Detailed biography for about page')),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('resume', models.FileField(blank=True, upload_to='resume/')),
                ('profile_image', models.ImageField(upload_to='profile/')),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description')),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords', max_length=255)),
                ('enable_dark_mode', models.BooleanField(default=True)),
                ('primary_color', models.CharField(default='#1E3A8A', help_text='Primary color in hex format', max_length=7)),
                ('accent_color', models.CharField(default='#0D9488', help_text='Accent color in hex format', max_length=7)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('FRONT', 'Frontend'), ('BACK', 'Backend'), ('DB', 'Database'), ('DEVOPS', 'DevOps'), ('DESIGN', 'Design'), ('OTHER', 'Other')], max_length=10)),
                ('proficiency', models.IntegerField(help_text='Skill level from 1-100')),
                ('icon', models.CharField(blank=True, help_text='Icon class (from included icon set)', max_length=50)),
            ],
            options={
                'ordering': ['-proficiency', 'category', 'name'],
            },
        ),
    ]
